/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar for the "docs" section of your site
 - List of docs to show in the sidebar
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Foundations of Physical AI',
      items: [
        {type: 'autogenerated', dirName: 'module1'}
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Human Locomotion & Control',
      items: [
        {type: 'autogenerated', dirName: 'module2'}
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Perception & Intelligence',
      items: [
        {type: 'autogenerated', dirName: 'module3'}
      ],
    },
    {
      type: 'category',
      label: 'Module 4: HRI, Safety & Ethics',
      items: [
        {type: 'autogenerated', dirName: 'module4'}
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;